name: Update GitBook Docs

on: [workflow_dispatch]
jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: NethermindEth/docs
          submodules: recursive
          path: nethermind
      - uses: actions/checkout@v2.3.4
      - name: Generate new docs
        run: |
          cd nethermind/
          cd src/Nethermind/Nethermind.GitBook
          dotnet run -c Release Nethermind.GitBook.csproj
      - name: Copy updated content to root
        run: |
          cp nethermind/gitbook/docs/ethereum-client/json-rpc/json-rpc-modules/* ethereum-client/json-rpc/json-rpc-modules/
          cp nethermind/gitbook/docs/ethereum-client/metrics/modules/* ethereum-client/metrics/modules
          cp nethermind/gitbook/docs/ethereum-client/configuration/modules/* ethereum-client/configuration/modules
          cp nethermind/gitbook/docs/ethereum-client/cli/cli-modules/* ethereum-client/cli/cli-modules
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update documentation
          body: |
            Nethermind documentation has been updated.
            
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          title: 'Updating Documentation'
          labels: documentation
          author-name: github-actions[bot]
          author-email: 41898282+github-actions[bot]@users.noreply.github.com
          committer-name: GitHub
          committer-email: noreply@github.com
          branch: docs-update
          branch-suffix: short-commit-hash
          base: master
      - name: Checking Outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
